name: 'HuskTowns'
description: 'Simple and elegant proxy-compatible Towny-style protection'
author: 'William278'
website: 'https://william278.net/project/husktowns'
main: 'net.william278.husktowns.BukkitHuskTowns'
version: '${version}'
api-version: 1.16
libraries:
  - 'mysql:mysql-connector-java:${mysql_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
softdepend:
  - 'Vault'
  - 'RedisEconomy'
  - 'dynmap'
  - 'BlueMap'
  - 'LuckPerms'
  - 'HuskHomes'
  - 'Plan'

commands:
  husktowns:
    usage: '/husktowns [<args>]'
  town:
    usage: '/town [<args>]'
    aliases: [ 't' ]
  admintown:
    usage: '/admintown [<args>]'
    aliases: [ 'at' ]