name: 'HuskTowns'
description: 'Simple and elegant proxy-compatible Towny-style protection'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.husktowns.BukkitHuskTowns'
version: '${version}'
api-version: 1.16
libraries:
  - 'mysql:mysql-connector-java:${mysql_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'